django_projects/banking_app/api/urls.py
from rest_framework import routers
from .users import views as UserViews
from .user_profile import views as UserProfilesViews 
from .accounts import views as AccountViews
from .transaction import views as TransactionViews
from .bills import views as BillViews


router = routers.DefaultRouter()
router.register(r'users', UserViews.UserViewSet, basename="users")
router.register(r'profiles', UserProfilesViews.UserProfileViewSet, basename="profiles")
router.register(r'accounts', AccountViews.AccountViewSet, basename="accounts")
router.register(r'transactions', TransactionViews.TransactionsViewSet, basename='transactions')
router.register(r'bills', BillViews.BillViewSet, basename='bills')
urlpatterns = router.urls

django_projects/banking_app/banking_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('transactions/', include(('transactions.urls', 'transactions'), namespace='transactions')),
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_projects/banking_app/transactions/urls.py
from django.urls import path
from .views import (TransactionPostView,
                    AccountListView,
                    CreateAccountView,
                    TransactionListView,
                    BillCreateView,
                    UserTransactionsListView,
                    find_account,
                    my_combined_view,
                    generate_account_number,
                    customer_profile_view)

urlpatterns = [
    path('transact/', TransactionPostView.as_view(), name="transact"),
    path('transact/history/', TransactionListView.as_view(), name="transact_history"),
    path('acc-inspect/', AccountListView.as_view(), name="acc_inspect"),
    path('acc-inspect/<int:pk>/', my_combined_view,
         name="single_acc_inspect"),
    path('create-account/', CreateAccountView.as_view(), name="create_account"),
    path('pay-bills/', BillCreateView.as_view(), name="pay_bills"),
    path('user/history/', UserTransactionsListView.as_view(), name="user_transactions"),
    path('user-profile/<int:pk>', customer_profile_view, name="user_profile"),
    path('find-account/', find_account, name="find_account"),
    path('gen-acc/', generate_account_number, name="gen_acc"),
]

django_projects/banking_app/transactions/models.py
from django.db import models
from django.urls import reverse
from profiles.models import User
from datetime import date, timedelta


# validators
def validate_amount(value):
    if value < 100:
        raise ValueError("To low to process the transaction")


class Account(models.Model):
    customer = models.OneToOneField(User, on_delete=models.CASCADE, related_name='account')
    account_num = models.CharField(
        max_length=13, unique=True, blank=False, null=False)
    balance = models.DecimalField(
        default=0.00, decimal_places=2, max_digits=10)
    date_opened = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.account_num}"

    def get_absolute_url(self):
        return reverse("transactions:single_acc_inspect", kwargs={"pk": self.customer.id})

    class Meta:
        ordering = ["-date_opened"]


class Transactions(models.Model):
    BOOLEAN_CHOICES = (
        ("Deposit", 'Deposit'),
        ("Withdraw", 'Withdraw'),
    )
    account = models.ForeignKey(Account, related_name='transactions', on_delete=models.CASCADE)
    account_num = models.CharField(max_length=13, null=False, blank=False)
    amount = models.DecimalField(
        decimal_places=2, max_digits=10, validators=[validate_amount])
    date_done = models.DateField(auto_now=True)
    description = models.CharField(max_length=250, null=True)
    type = models.CharField(choices=BOOLEAN_CHOICES, max_length=250)

    def __str__(self) -> str:
        return f"{self.id}"

    def get_absolute_url(self):
        return reverse("transactions:transact")

    class Meta:
        ordering = ['-date_done']


class Card(models.Model):
    customer = models.OneToOneField(User, on_delete=models.CASCADE)
    card_type = models.CharField(max_length=250)
    card_number = models.CharField(max_length=250, unique=True)
    expiration_date = models.DateField(default=date.today() + timedelta(365))
    is_active = models.BooleanField(default=True)
    issue_date = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.customer.first_name}"


class BillInfo(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    payee_name = models.CharField(max_length=250)
    payee_account = models.ForeignKey(
        Account, on_delete=models.SET_NULL, null=True)
    amount=models.PositiveIntegerField()
    payment_date = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.customer.email}"

    def get_absolute_url(self):
        return reverse("transactions:pay_bills")
    
    class Meta:
        ordering = ['-payment_date']

django_projects/banking_app/transactions/forms.py
from django import forms
from .models import Account, BillInfo

class BillForm(forms.ModelForm):
    payee_acc = forms.CharField(max_length=13, required=True, label="Payee Account Number")

    class Meta:
        model = BillInfo
        fields = ["payee_acc", "payee_name", "amount"]

class AccountCreationForm(forms.ModelForm):
    phone_number = forms.CharField(max_length=13, required=True)

    class Meta:
        model = Account
        fields = ["phone_number", "account_num", "balance"]

django_projects/banking_app/api/accounts/views.py
from api.transaction.serializers import TransactionSerializer
from profiles.models import User
from transactions.models import Account, Transactions
from rest_framework.viewsets import ModelViewSet
from rest_framework.decorators import action
from .serializers import AccountSerializer
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import IsAdminUser
from .helpers import IsManagerOrTeller, IsOwner


    
class AccountViewSet(ModelViewSet):
    queryset = None
    serializer_class = AccountSerializer

    def get_permissions(self):
        if self.action in ['retrieve', 'list']:
            self.permission_classes = [IsAdminUser | IsManagerOrTeller | IsOwner]
        elif self.action in ['update', 'destory', 'patch']:
            self.permission_classes = [IsAdminUser]
        else:
            self.permission_classes = [IsManagerOrTeller | IsAdminUser]
        return [permission() for permission in self.permission_classes]
        
    def get_queryset(self):
        queryset = Account.objects.all()
        try:
            if self.request.user.type == 'CUSTOMER':
                AccountViewSet.queryset = queryset.filter(
                    account_num=self.request.user.account.account_num).all()
                queryset = AccountViewSet.queryset
            AccountViewSet.queryset = queryset

            return queryset
        except Exception as e:
            return Response({"errors": str(e), "message": "Something wrong happened"},
                            status=status.HTTP_400_BAD_REQUEST)
        return queryset

    def get_object(self):
        obj = super().get_object()
        self.check_object_permissions(self.request, obj)
        return obj
    

    def list(self, request):
        serializer = AccountSerializer(Account.objects.all(), many=True)
        print()
        return Response(serializer.data,  status=status.HTTP_200_OK)

    def retrieve(self, request, pk=None):
        account = self.get_object()
        serialzer = AccountSerializer(account)
        return Response(serialzer.data, status=status.HTTP_200_OK)
        
    def create(self, request):
        data= request.data.copy()
        try:
            telephone = data.pop('telephone')
            user = User.objects.filter(telephone=telephone).first()
            if not user:
                raise ValueError("No user found")
            data['customer'] = user.id
            serializer = self.get_serializer(data=data)
            serializer.is_valid(raise_exception=True)
            serializer.save()
            return Response({"data": serializer.data, 
                             "message": f"Account created successfully with {serializer.data.get('balance')}"},
                            status=status.HTTP_201_CREATED)
        except Exception as e:
            return Response({"errors": str(e)}, status=status.HTTP_400_BAD_REQUEST)


    def destroy(self, request, pk=None):
        try:
            account = self.get_object()
            account.delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        except Account.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)


    @action(detail=False, methods=["GET"],url_path='gen-acc-num', 
            url_name='gen_acc_num', permission_classes = [IsAdminUser | IsManagerOrTeller])
    def generate_account_num(self, request):
        from datetime import datetime
        today = str(datetime.now()).replace(
            ":", "").replace("-", "").replace(".", "").replace(" ", "")
        today = today[:13]
        return Response({"data": today, 
                         "message": "Account number generated successfully"})

    @action(detail=True, methods=["GET"], url_path='acc-transactions',
            url_name='acc_transactions', permission_classes = [IsAdminUser | IsManagerOrTeller |IsOwner])
    def account_transactions(self, request, pk=None):
        account = self.get_object()
        trans = account.transactions.all()
        serializer = TransactionSerializer(trans, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    @action(detail=True, methods=["GET"], url_path='acc-transactions-one/(?P<trans_id>\d+)',
            url_name="single_account_trans", permission_classes=[IsAdminUser | IsManagerOrTeller | IsOwner])
    def account_transactions_single(self, request, pk=None, trans_id=None):
        account = self.get_object()
        trans = account.transactions.filter(pk=trans_id).first()
        serializer = TransactionSerializer(trans)
        return Response(serializer.data, status=status.HTTP_200_OK)
    
    
    @action(detail=False, methods=["GET"], url_path='acc-amt-range', url_name='acc_amt_range',
             permission_classes=[IsAdminUser | IsManagerOrTeller])
    def account_amount_range(self, request):
        res = {}
        try:
            data = request.query_params
            for k in data.keys():
                if k not in ['from_bal', 'to_bal']:
                    return Response({"errors": "Please provide correct query params"},
                                    status=status.HTTP_400_BAD_REQUEST)
            if not data.get('from_bal') and data.get('to_bal'):
                res = self.queryset.filter(balance__lte=data.get('to_bal')).all()
                serializer = AccountSerializer(res, many=True)
                return Response(serializer.data, status=status.HTTP_200_OK)
            if data.get('from_bal') and not data.get('to_bal'):
                res = self.queryset.filter(
                    balance__gte=data.get('from_bal')).all()
                serializer = AccountSerializer(res, many=True)
                return Response(serializer.data, status=status.HTTP_200_OK)
            res = self.queryset.filter(balance__gte=data.get('from_bal'),
                                       balance__lte=data.get('to_bal')).all()
            serializer = AccountSerializer(res, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({"errors": str(e), "message": "Something went wrong, try again!"},
                            status=status.HTTP_400_BAD_REQUEST)
    
    @action(detail=False, methods=["POST"], url_path='s-acc-ctm', url_name='s_acc_ctm',
             permission_classes =[IsAdminUser | IsManagerOrTeller])
    def account_by_customer(self, request):
        try:
            data = request.data
            res = self.queryset.filter(customer_phone_number=data.get('phone_number')).first()
            if res:
                serializer = AccountSerializer(res)
                return Response(serializer.data)
            return Response({"message": "Enter correct Phone number"})
        except Exception as e:
            return Response({"errors": str(e), "message": "Something went wrong, try again!"},
                            status=status.HTTP_400_BAD_REQUEST)
    
    @action(detail=False, methods=["GET"], url_path='acc-btn', url_name='acc_btn',
            permission_classes=[IsAdminUser | IsManagerOrTeller | IsOwner])
    def opened_btn_date(self, request):
        res = {}
        try:
            data = request.query_params
            for k in data.keys():
                if k not in ['from_date', 'to_date']:
                    return Response({"errors": "Please provide correct query params"},
                                    status=status.HTTP_400_BAD_REQUEST)
            if not data.get('from_date') and data.get('to_date'):
                res = self.queryset.filter(date_opened__lte=data.get('to_date')).all()
                serializer = AccountSerializer(res, many=True)
                return Response(serializer.data, status=status.HTTP_200_OK)
            if data.get('from_date') and not data.get('to_date'):
                res = self.queryset.filter(
                    date_opened__gte=data.get('from_date')).all()
                serializer = AccountSerializer(res, many=True)
                return Response(serializer.data, status=status.HTTP_200_OK)
            res = self.queryset.filter(date_opened__gte=data.get('from_date'),
                                        date_opened__lte=data.get('to_date')).all()
            serializer = AccountSerializer(res, many=True)
            return Response(serializer.data, status=status.HTTP_200_OK)
        except Exception as e:
            return Response({"errors": str(e), "message": "Something went wrong, try again!"}, 
                            status=status.HTTP_400_BAD_REQUEST)

django_projects/banking_app/transactions/templates/transactions/404_error_customer.html
{% extends "profiles/user_base.html" %}
{% load static %}
{% block navigation %}
    <title>404 Not Found</title>
    <link rel="stylesheet" href="{% static 'transactions/inspect.css' %}">
{% endblock %}
{% block content %}
    <h1 style="text-align: center; color: red;">NOT FOUND</h1>
{% endblock %}

django_projects/banking_app/transactions/templates/transactions/404_error_teller.html
{% extends "profiles/base.html" %}
{% load static %}
{% block navigation %}
    <title>404 Not Found</title>
    <link rel="stylesheet" href="{% static 'transactions/inspect.css' %}">
{% endblock %}
{% block content %}
    <h1 style="text-align: center; color: red;">NOT FOUND</h1>
{% endblock %}

django_projects/banking_app/transactions/templates/transactions/acc_inspection.html
{% extends "profiles/base.html" %}
{% load static %}
{% block navigation %}
    <title>Account Inspection</title>
    <link rel="stylesheet" href="{% static 'transactions/inspect.css' %}">
{% endblock %}

{% block content %}

<div class="container">
    <h1>ACCOUNT INSEPCTION</h1>
    
    <div class="btn-navigation">
        <form action="{% url 'transactions:acc_inspect' %}" method="GET">
            <label for="account_num">Filter By Account Number</label>
            <input type="text" name="account_num" id="">
            <button type="submit">Search</button>
        </form>
    </div>
    <table>
        <tr>
            <th>Customer</th>
            <th>Account Number</th>
            <th>Date Opened</th>
            <th>Balance</th>
        </tr>
        {% for account in accounts %}            
            <tr>
                <a href=""></a>
                <td><a href="{% url 'transactions:single_acc_inspect' account.customer.id %}">{{account.customer}}</a></td>
                <td>{{account.account_num}}</td>
                <td>{{account.date_opened}}</td>
                <td>{{account.balance}}</td>
            </tr>
        {% endfor %}
    </table>
</div>

{% endblock %}

django_projects/banking_app/transactions/templates/transactions/account_detail.html
{% extends "profiles/base.html" %}
{% load static %}
{% block navigation %}
    <title>Account Details</title>
    <link rel="stylesheet" href="{% static 'transactions/inspect.css' %}">
{% endblock %}
{% block content %}
<div class="container">
    <h2>ACCOUNT SUMMARY</h2>
    {% if messages %}
        <div class="messages">
        {% for msg in messages %}
            {% if msg.tags == 'error' %}
            <p style="color: rgb(255, 47, 0)">{{msg}}</p>
            {% else %}
            <small style="color: rgb(0, 132, 255)">{{msg}}</small>
            {% endif %}
        {% endfor %}
        </div>
    {% endif %}
    <table>
        <tr>
            <th>Customer</th>
            <th>Account Number</th>
            <th>Date Opened</th>
            <th>Balance</th>
        </tr>
        <tr>
            <td>{{account.customer}}</td>
            <td>{{account.account_num}}</td>
            <td>{{account.date_opened}}</td>
            <td>{{account.balance}}</td>
        </tr>
    </table>
    <h2>ACCOUNT TRANSACTION SUMMARY</h2>
    <table>
        <tr>
            <th>Account</th>
            <th>Amount</th>
            <th>Date Done</th>
            <th>Description</th>
            <th>Type</th>
        </tr>
        {% for transac in list_data %}
            <tr>
                <td>
                    {{transac.account}}
                </td>
                <td>
                    {{transac.amount}}
                </td>
                <td>
                    {{transac.date_done}}
                </td>
                <td>
                    {{transac.description}}
                </td>
                <td>
                    {{transac.type}}
                </td>
            </tr>
        {% endfor %}
    
    </table>
    <a href="{% url 'transactions:acc_inspect' %}">Back</a>
</div>


{% endblock %}

django_projects/banking_app/transactions/templates/transactions/account_form.html
{% extends "profiles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block navigation %}
    <link rel="stylesheet" type="text/css" href="{% static 'transactions/deposit.css' %}" />
    <title>Create account</title>
  {% endblock %}
  <body>
    {% block content %}
    <h1 style="text-align: center; margin-top: 3vh;">CREATE ACCOUNT FOR CUSTOMER</h1>
    <div class="contents">
      <div class="btn-navigation">
        <form action="{% url 'transactions:gen_acc' %}" method="GET">
          <label for="account_num">Generate Account Number</label>
          <button type="submit">Generate</button>
        </form>
        {% if messages %}
          <div class="messages">
            {% for msg in messages %}
              {% if msg.tags == 'error' %}
                <p style="color: rgb(255, 47, 0)">{{msg}}</p>
              {% else %}
                <small style="color: rgb(0, 132, 255)">{{msg}}</small>
                <small style="color: rgb(0, 132, 255)">{{msg.tags}}</small>
              {% endif %}
            {% endfor %}
          </div>
        {% endif %}
      </div>
      <div class="trans-forms">
        <form action="" method="POST" id="post-form">
          {% csrf_token%} {{form|crispy}}
          <button type="submit">Create Account</button>
        </form>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

django_projects/banking_app/transactions/templates/transactions/billinfo_form.html
{% extends "profiles/user_base.html" %}
{% load crispy_forms_tags %}
{% load static%}
<!DOCTYPE html>
<html lang="en">
  {% block navigation %}
  <link
    rel="stylesheet"
    type="text/css"
    href="{% static 'transactions/deposit.css' %}"
  />
  <title>Pay Bills</title>
  {% endblock %}
  <body>
    {% block content %}
    <h1 style="text-align: center; margin-top: 3vh">PAY BILLS</h1>
    <div class="contents">
     {% if messages %}
        <div class="messages">
          {% for msg in messages %}
            {% if msg.tags == 'error' %}
              <p style="color: rgb(255, 47, 0)">{{msg}}</p>
            {% else %}
              <small style="color: rgb(0, 132, 255)">{{msg}}</small>
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
      <div class="trans-forms">
        <form action="" method="POST" id="post-form">
          {% csrf_token%} {{form|crispy}}
          <button type="submit">Pay</button>
        </form>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

django_projects/banking_app/transactions/templates/transactions/deposit.html
{% extends "profiles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block navigation %}
    <link rel="stylesheet" type="text/css" href="{% static 'transactions/deposit.css' %}" />
    <title>Make Deposit</title>
  {% endblock %}
  <body>
    {% block content %}
    <h1 style="text-align: center; margin-top: 3vh;">TELLER TRANSACTION BOARD</h1>
    <div class="contents">
      <div class="btn-navigation">
        <form action="{% url 'transactions:find_account' %}" method="GET">
          <label for="account_num">Search Account Number</label>
          <input type="number" name="account_num" id="" />
          <button type="submit">Search</button>
        </form>
        {% if messages %}
          <div class="messages">
            {% for msg in messages %}
              {% if msg.tags == 'error' %}
                <p style="color: rgb(255, 47, 0)">{{msg}}</p>
              {% else %}
                <small style="color: rgb(0, 132, 255)">{{msg}}</small>
              {% endif %}
            {% endfor %}
          </div>
        {% endif %}
      </div>
      <div class="trans-forms">
        <form action="" method="POST" id="post-form">
          {% csrf_token%} {{form|crispy}}
          <button type="submit">Record Transaction</button>
        </form>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

django_projects/banking_app/transactions/templates/transactions/teller_details.html
{% extends "profiles/base.html" %}
{% load crispy_forms_tags %}
{% load  static %}
{% block navigation %}
    <title>Account Information</title>
    <link rel="stylesheet" href="{% static 'transactions/inspect.css' %}">

    <style>
        .profile-picture{
            width: 130px;
            height: 130px;
            overflow: hidden;
            border-radius: 50%;
            display: flex;
            align-items: center;
            flex-direction: column;
        }
        .profile-picture img{
            box-shadow: 0 0 10px black;
            width: 100%;
            height: 200px;
        }
        .contents{
            display: flex;
            margin-bottom: 100px;
            margin-top: 20px;
            margin-left: 50%;
            transform: translateX(-50%);
            padding: 20px;
            border-radius: 4px;
            background-color: rgb(231, 228, 223);
        }
        .profile-content{
            margin-left: 20px;
        }

        form{
            margin-top: 20px;
            border-top: 2px solid black;
        }
        button{
            padding: 5px 10px;
            border: none;
            cursor: pointer;
            background-color: #0aa9cc;
            color: white;
            margin-top: 20px;
        }
        button:hover{
            background-color: #4CAF50;
        }
        p{
            background-color: #0aa9cc;
            color: white;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="contents">
        <div class="profile-picture">
            <img src="{{user.profile.image.url}}" alt="Image">
        </div>
        <div class="profile-content">
            <div class="user-info">
                <h2>USER INFO</h2>
                <div class="splitter">
                    <legend>FIRST NAME</legend>
                    <p>{{user.first_name}}</p>
                </div>
                <div class="splitter">
                    <legend>LAST NAME</legend>
                    <p>{{user.last_name}}</p>
                </div>
                <div class="splitter">
                    <legend>EMAIL</legend>
                    {% if user.email %}
                        <p>{{user.email}}</p>
                    {% else %}
                        <i><small style="background-color: lightgrey;">No Email</small></i>
                    {% endif %}
                </div>
                <div class="splitter">
                    <legend>TELEPHONE</legend>
                    <p>{{user.telephone}}</p>
                </div>
            </div>
            <form method="POST" enctype="multipart/form-data">
                <h1>UPDATE PROFILE PICTURE</h1>
                {% csrf_token %}
                {{profile_form.image}}
                <br>
                <button type="submit">Update</button>
            </form>
        </div>
    </div>
{% endblock %}

django_projects/banking_app/transactions/templates/transactions/transactions_list.html
{% extends "profiles/base.html" %}
{% load  static %}
{% block navigation %}
    <title>Transaction Inspection</title>
    <link rel="stylesheet" href="{% static 'transactions/inspect.css' %}">
{% endblock %}

{% block content %}
    <div class="container">
        <h1>TRANSACTION INSEPCTION</h1>
        <div class="btn-navigation">
            <form action="{% url 'transactions:transact_history' %}" method="GET">
                <label for="account_num">Filter By Account Number</label>
                <input type="text" name="account_num" id="">
                <button type="submit">Search</button>
            </form>
        </div>
        <table>
            <tr>
                <th>Account Number</th>
                <th>Amount</th>
                <th>Description</th>
                <th>Type</th>
                <th>Date Done</th>
            </tr>
            {% for trans in object %}            
                <tr>
                    <td>{{trans.account_num}}</td>
                    <td>{{trans.amount}}</td>
                    <td>{{trans.description}}</td>
                    <td>{{trans.type}}</td>
                    <td>{{trans.date_done}}</td>
                </tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

django_projects/banking_app/transactions/templates/transactions/user_account_info.html
{% extends "profiles/user_base.html" %}
{% load  static %}
{% block navigation %}
    <title>Account Info</title>
    <link rel="stylesheet" href="{% static 'transactions/inspect.css' %}">

    <style>
        .contents{
            margin-top: 30px;
            margin-left: 50%;
            transform: translateX(-50%);
            background-color: rgb(247, 247, 247);
            box-shadow: 0 0 2px black;
            padding: 20px;
            border-radius: 5px;
        }
        .splitter{
            background-color: #0aa9cc;
            margin-top: 5px;
            color: white;
            border-radius: 5px;
            padding: 0 20px;
        }

        .splitter h2{
            color: rgb(247, 247, 209);
        }
    </style>
{% endblock %}

{% block content %}
    <div class="contents">
        WE ARE!
        {{object}}
        <h2>ACCOUNT INFORMATION</h2>
        <div class="splitter">
            <legend>OWNER</legend>
            <h2>{{object.customer}}</h2>
        </div>
        <div class="splitter">
            <legend>TELEPHONE</legend>
            <h2>{{object.customer_phone_number}}</h2>
        </div>
        
        <div class="splitter">
            <legend>ACCOUNT NUMBER</legend>
            <h2>{{object.account_num}}</h2>
        </div>
        
        <div class="splitter">
            <legend>ACCOUNT BALANCE</legend>
            <h2>{{object.balance}}</h2>
        </div>
        
        <div class="splitter">
            <legend>DATE OPENED</legend>
            <h2>{{object.date_opened}}</h2>
        </div>
    </div>
{% endblock %}

django_projects/banking_app/transactions/templates/transactions/user_detail.html
{% extends "profiles/user_base.html" %}
{% load  static %}
{% block navigation %}
    <title>Account Information</title>
    <link rel="stylesheet" href="{% static 'transactions/inspect.css' %}">

    <style>
        .profile-picture{
            width: 130px;
            height: 130px;
            overflow: hidden;
            border-radius: 50%;
            display: flex;
            align-items: center;
            flex-direction: column;
        }
        .profile-picture img{
            box-shadow: 0 0 10px black;
            width: 100%;
            height: 200px;
        }
        .contents{
            display: flex;
            margin-bottom: 100px;
            margin-top: 20px;
            margin-left: 50%;
            transform: translateX(-50%);
            padding: 20px;
            border-radius: 4px;
            background-color: rgb(231, 228, 223);
        }
        .profile-content{
            margin-left: 20px;
        }

        form{
            margin-top: 20px;
            border-top: 2px solid black;
        }
        button{
            padding: 5px 10px;
            border: none;
            cursor: pointer;
            background-color: #0aa9cc;
            color: white;
            margin-top: 20px;
        }
        button:hover{
            background-color: #4CAF50;
        }
        p{
            background-color: #0aa9cc;
            color: white;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="contents">
        <div class="profile-picture">
            <img src="{{user.profile.image.url}}" alt="Image">
        </div>
        <div class="profile-content">
            <div class="user-info">
                <h2>USER INFO</h2>
                <div class="splitter">
                    <legend>FIRST NAME</legend>
                    <p>{{user.first_name}}</p>
                </div>
                <div class="splitter">
                    <legend>LAST NAME</legend>
                    <p>{{user.last_name}}</p>
                </div>
                <div class="splitter">
                    <legend>EMAIL</legend>
                    {% if user.email %}
                        <p>{{user.email}}</p>
                    {% else %}
                        <i><small style="background-color: lightgrey;">No Email</small></i>
                    {% endif %}
                </div>
                <div class="splitter">
                    <legend>TELEPHONE</legend>
                    <p>{{user.telephone}}</p>
                </div>
            </div>
            <form method="POST" enctype="multipart/form-data">
                <h1>UPDATE PROFILE PICTURE</h1>
                {% csrf_token %}
                <small>CHANGE PROFILE PICTURE</small>
                {{profile_form.image}}
                <br>
                <button type="submit">Update</button>
            </form>
        </div>
    </div>
{% endblock %}