django_projects/banking_app/api/urls.py
from rest_framework import routers
from .users import views as UserViews
from .user_profile import views as UserProfilesViews 
from .accounts import views as AccountViews
from .transaction import views as TransactionViews
from .bills import views as BillViews


router = routers.DefaultRouter()
router.register(r'users', UserViews.UserViewSet, basename="users")
router.register(r'profiles', UserProfilesViews.UserProfileViewSet, basename="profiles")
router.register(r'accounts', AccountViews.AccountViewSet, basename="accounts")
router.register(r'transactions', TransactionViews.TransactionsViewSet, basename='transactions')
router.register(r'bills', BillViews.BillViewSet, basename='bills')
urlpatterns = router.urls

django_projects/banking_app/banking_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profiles/', include(('profiles.urls', 'profiles'), namespace='profiles')),
    path('transactions/', include(('transactions.urls', 'transactions'), namespace='transactions')),
    path('api/v1/', include('api.urls')),
    path('api-auth/', include('rest_framework.urls'))
]

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django_projects/banking_app/profiles/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (CreateUserProfileView, login_view,
                    CustomerListView, UserAccountDetailView,
                    create_password,
                    register)
from profiles.views import customer_profile_view

urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', LogoutView.as_view(template_name="profiles/logout.html"), name='logout'),
    path('create-password/', create_password, name="create_password"),
    path('customers/', CustomerListView.as_view(), name="customers"),
    path('create-user/', register, name="create_user"),
    path('create-user-profile/', CreateUserProfileView.as_view(), name="create_user_profile"),
    path('user/account/<int:pk>/',
         UserAccountDetailView.as_view(), name='user_account'),
    path('user/<int:pk>', customer_profile_view, name="user_profile")

]

django_projects/banking_app/transactions/urls.py
from django.urls import path
from .views import (TransactionPostView,
                    AccountListView,
                    CreateAccountView,
                    TransactionListView,
                    BillCreateView,
                    UserTransactionsListView,
                    find_account,
                    my_combined_view,
                    generate_account_number,
                    customer_profile_view)

urlpatterns = [
    path('transact/', TransactionPostView.as_view(), name="transact"),
    path('transact/history/', TransactionListView.as_view(), name="transact_history"),
    path('acc-inspect/', AccountListView.as_view(), name="acc_inspect"),
    path('acc-inspect/<int:pk>/', my_combined_view,
         name="single_acc_inspect"),
    path('create-account/', CreateAccountView.as_view(), name="create_account"),
    path('pay-bills/', BillCreateView.as_view(), name="pay_bills"),
    path('user/history/', UserTransactionsListView.as_view(), name="user_transactions"),
    path('user-profile/<int:pk>', customer_profile_view, name="user_profile"),
    path('find-account/', find_account, name="find_account"),
    path('gen-acc/', generate_account_number, name="gen_acc"),
]

django_projects/banking_app/api/users/views.py
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.viewsets import ModelViewSet
from rest_framework.response import Response
from rest_framework.permissions import BasePermission, IsAdminUser, IsAuthenticated
from api.accounts.helpers import IsManagerOrTeller
from transactions.models import Account
from .serializers import (AccountSerializer,
                             CreateUserLeavePasswordSerializer,
                             UserSerializer,
                             PasswordSerializer, PhoneNumberSerializer,
                             )
from api.transaction.serializers import TransactionSerializer
from profiles.models import User


class IsOwner(BasePermission):
    def has_object_permission(self, request, view, obj):
        if not request.user.is_authenticated:
            return False
        if request.user != obj:
            return False
        return True

    def has_permission(self, request, view):
        if not request.user.is_authenticated:
            return False
        return True


class IsNotLoggedIn(BasePermission):

    def has_permission(self, request, view):
        if request.user.is_authenticated:
            return False
        return True
    
class UserViewSet(ModelViewSet):
    queryset = User.objects.all()

    def get_serializer(self, *args, **kwargs):
        if self.action == 'list':
            return UserSerializer(*args, **kwargs)
        if self.action in ['set_password']:
            return PasswordSerializer(*args, **kwargs)
        if self.action == 'find_user':
            return PhoneNumberSerializer(*args, **kwargs)
        return CreateUserLeavePasswordSerializer(*args, **kwargs)
    
    def get_permissions(self):
        if self.action in ['create']:
            self.permission_classes = [IsAdminUser | IsManagerOrTeller]
        if self.action in ['destroy', 'update']:
            self.permission_classes = [IsAdminUser]
        if self.action in ['retrieve', 'list']:
            self.permission_classes = [IsAdminUser |
                                       IsManagerOrTeller | IsOwner]
        return [permission() for permission in self.permission_classes]

    def get_queryset(self):
        if self.request.user.type == 'CUSTOMER':
            qs = self.queryset.filter(id=self.request.user.id).all()
            UserViewSet.queryset = qs
            return self.queryset
        else:
            return self.queryset

    def get_object(self):
        obj = super().get_object()
        self.check_object_permissions(self.request, obj)
        return obj

    def list(self, request):
        serializer = self.get_serializer(
            self. queryset, many=True)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def retrieve(self, request, pk=None):
        user = self.get_object()
        serializer = self.get_serializer(user)
        return Response(serializer.data, status=status.HTTP_200_OK)

    def create(self, request):
        try:
            serializer = CreateUserLeavePasswordSerializer(data=request.data)
            serializer.is_valid(raise_exception=True)
            instance = serializer.save()
            return Response({"message": f"User {instance.first_name} was created successfully"},
                            status=status.HTTP_201_CREATED)
        except Exception as e:
            return Response({"errors": str(e)}, status=status.HTTP_400_BAD_REQUEST)

    def update(self, request, pk=None):
        try:
            user = self.get_object()
            serializer = self.get_serializer(user, data=request.data, partial=True)

            if serializer.is_valid():
                serializer.save()
                return Response({"message": "Updated successfully", 
                                 "updated_fields": serializer.validated_data}, 
                                 status=status.HTTP_201_CREATED)
            else:
                return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        except User.DoesNotExist:
            return Response(status=status.http400)

    def destroy(self, request, pk=None):
        try:
            user = self.get_object()
            user.delete()
            return Response(status=status.HTTP_204_NO_CONTENT)
        except User.DoesNotExist:
            return Response(status=status.HTTP_404_NOT_FOUND)

    @action(detail=True, methods=['GET'], url_path='user-acc', url_name='user_account',
            permission_classes=[IsAdminUser|IsManagerOrTeller|IsOwner])
    def user_accounts(self, request, pk=None):
        try:
            user = self.get_object()
            serializer = AccountSerializer(user.account)
            return Response({"status": "OK", "data": serializer.data})
        except User.account.RelatedObjectDoesNotExist:
            return Response({"message": "User has no account"})

        except User.DoesNotExist:
            return Response(status=status.HTTP_400_BAD_REQUEST)

    @action(detail=True, methods=["GET"], url_path='user-acc-trans', 
            url_name='user_account_transactions', permission_classes=[IsAdminUser | IsManagerOrTeller | IsOwner])
    def user_account_transactions(self, request, pk=None):
        try:
            user = self.get_object()
            account = user.account
            if account:
                queryset = account.transactions.all()
                serializer = TransactionSerializer(queryset, many=True)
                return Response({"status": "OK", "data": serializer.data})
            else:
                return Response({"message": f"There is no any transaction \
                                 for {user.first_name}'s account."})
        except User.account.RelatedObjectDoesNotExist:
            return Response({"message": "User has no account"})

        except User.DoesNotExist:
            return Response(status=status.HTTP_400_BAD_REQUEST)

    @action(detail=False, methods=["POST"], url_path='find-user', url_name='find_user', 
            permission_classes=[IsAdminUser | IsManagerOrTeller])
    def find_user(self, request):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        user = User.objects.filter(
            telephone=serializer.validated_data["telephone"]).first()
        if user:
            user_serializer = UserSerializer(user)
            return Response({"user": user_serializer.data, "message": "User found"},
                             status=status.HTTP_200_OK)
        return Response({"message": "No user found"}, status=status.HTTP_404_NOT_FOUND)

    @action(detail=False, methods=["POST"], url_path='set-password', url_name='set_password',
            permission_classes=[IsNotLoggedIn])
    def set_password(self, request):
        try:
            serializer = self.get_serializer(data=request.data)
            serializer.is_valid(raise_exception=True)
            return Response({"message": "Password has been set"},
                                status=status.HTTP_202_ACCEPTED)
        except Exception as e:
            return Response({"errors": str(e), "message": "Something went wrong"}, 
                            status=status.HTTP_400_BAD_REQUEST)

django_projects/banking_app/profiles/views.py
from typing import Any
from django.contrib.auth.hashers import make_password
from django.contrib.auth.views import LoginView
from django.http.response import HttpResponse as HttpResponse
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.contrib import messages
from django.shortcuts import render, redirect
from banking_app.serializer import Serializer
from transactions.models import Account
from transactions.views import UserAccessMixin
from .models import User, Profile
from django.views.generic import CreateView, ListView, DetailView
from .forms import (CustomUserUpdateForm, ProfileCrationForm,
                    UserCreationModelForm, 
                    UserAuthenticationForm,
                    PasswordCreationForm, LoginForm)
from .helpers import TestUserMixin, check_permission


@check_permission(perms=["profiles.add_user", "profiles.view_user"])
def register(request):
    try:
        if request.method == 'POST':
            form = UserCreationModelForm(request.POST)
            if form.is_valid():
                print(form.cleaned_data)
                user = form.save(commit=False)
                user.save()
                return redirect('profiles:customers')
        else:
            form = UserCreationModelForm()
        return render(request, 'profiles/user_form.html', {'form': form})
    except Exception as e:
        messages.error(request, str(e))
        return redirect("profiles:create_user")
        

def create_password(request):
    """Allow customer to create password"""
    form = PasswordCreationForm

    if request.user.is_authenticated:
        if request.user.type == "CUSTOMER":
            return redirect("transactions:pay_bills")
        elif request.user.type == "TELLER":
            return redirect("transactions:transact")
        else:
            return redirect("admin:index")
    
    if request.method == 'POST':
        form = PasswordCreationForm(request.POST)
        if form.is_valid():
            _ = form.save(commit=False)
            tel = form.cleaned_data.get("telephone")
            _user = User.objects.filter(telephone=tel).first()
            if _user:
                if _user.password:
                    messages.info(request, "Passwrd Already Set!")
                    return redirect("profiles:login")
                _user.password = make_password(request.POST['password1'])
                _user.save()
                messages.success(request, "Password Successfully Created")
                return redirect("profiles:login")
            messages.error(request, "No User Found")
            return redirect("profiles:create_password")
    return render(request, 'profiles/create_password.html', {'form': form})


class CreateUserProfileView(UserAccessMixin, CreateView):
    model = Profile
    form_class = ProfileCrationForm
    permission_required = ["profiles.add_user"]
    success_url = "create_user_profile"
    template_name = 'profiles/customerprofile_form.html'
    
    def form_valid(self, form):
        customer = User.objects.filter(
            telephone=form.cleaned_data["telephone"]).first()
        
        try:
            self.object = form.save(commit=False)
            self.object.customer_id = Serializer.dumps(customer)["id"]
            messages.success(request=self.request, message="Customer profile created successfully")
            super().form_valid(form)
            return redirect("profiles:create_user_profile")
        except Exception as e:
            print(str(e))
            messages.error(request=self.request, message="Customer profile is not created")
            return super().form_invalid(form)


class CustomerListView(UserAccessMixin, ListView):
    model = User
    context_object_name = "customers"
    permission_required = ["profiles.view_user"]


def customer_profile_view(request, pk):
    user_info = UserCreationModelForm

    try:
        if request.method == 'POST':
            profile_form = CustomUserUpdateForm(request.POST, request.FILES, instance=request.user.profile)
            if profile_form.is_valid():
                profile_form.save()
                return redirect(reverse("profiles:user_profile", kwargs={"pk": request.user.id}))
        else:
            profile_form = CustomUserUpdateForm(instance=request.user.profile)
            return render(request, 'transactions/user_detail.html', {'user_form': user_info,
                                                            "profile_form":  profile_form})
    except Exception as e:
        print(e)
        return render(request, "transactions/404_error_customer.html")

class CustomerDetailView(DetailView):
    model = User


class UserAccountDetailView(TestUserMixin, DetailView):
    model = Account
    template_name = "transactions/user_account_info.html"
    context_object_name = "object"


from django.contrib.auth import authenticate, login

def login_view(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            telephone = form.cleaned_data["telephone"]
            password = form.cleaned_data["password"]
            user_from_db = User.objects.filter(telephone=telephone).first()
            if not user_from_db.password:
                messages.info(request, "Please create password first")
                return redirect("profiles:create_password")
            user = authenticate(request, username=telephone, password=password)
            if not user:
                messages.error(request=request, message="Incorrect credentials, try again! Or set password if you're new o system")
                return redirect("profiles:login")
            login(request, user)
            if request.user.type == "ADMIN":
                return redirect("admin:index")
            elif request.user.type == "CUSTOMER":
                return redirect("transactions:pay_bills")
            else:
                return redirect("transactions:transact")

    return render(request=request, template_name="profiles/login.html", context={'form': form})

django_projects/banking_app/profiles/templates/profiles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'profiles/style/common.css' %}"
    />
    <link rel="icon" href="/media/logo.png">
    {% block navigation %}
    
    {% endblock %}
  </head>
  <body>
    <header>
      <nav>
        <div class="left">
          <a href="{% url 'transactions:transact' %}">
            <img src="/media/logo.png" alt="LOGO" width="40px" height="40px">
            <h1>LA BANK</h1>
          </a>
        </div>
        <div class="right">
            {% if user.is_authenticated %}
            <ul>
              <small>Welcome, {{user.first_name}}.</small>
              <div class="dropdown">
                <li><a href="" >TRANSACT</a></li>
                  <div class="dropdown-content">
                    <ul>
                      <li><a href="{% url 'transactions:transact' %}">TELLER BOARD</a></li>
                      <li><a href="{% url 'transactions:transact_history' %}">TRANSACTION INSPECTION</a></li>
                    </ul>
                  </div>
              </div>
              <div class="dropdown">
                <li><a href="{% url 'transactions:acc_inspect' %}" >ACCOUNT</a></li>
                  <div class="dropdown-content">
                    <ul>
                      <li><a href="{% url 'transactions:create_account' %}">CREATE ACCOUNT</a></li>
                      <li><a href="{% url 'transactions:acc_inspect' %}">ACCOUNT INSEPECTION</a></li>
                    </ul>
                  </div>
              </div>
              <div class="dropdown">
                <li><a href="" >CUSTOMER</a></li>
                  <div class="dropdown-content">
                    <ul>
                      <li><a href="{% url 'profiles:create_user' %}">CUSTOMER MANAGEMENT</a></li>
                      <li><a href="{% url 'profiles:customers' %}">CUSTOMER INSPECTION</a></li>
                    </ul>
                  </div>
              </div>
              <li><a href="{% url 'transactions:user_profile' user.id%}">PROFILE</a></li>
              <form action="{% url 'profiles:logout' %}" method="POST" style="background-color: transparent; 
                                                                        border:none; box-shadow: none; width: auto; 
                                                                        height: auto; margin-top:0; padding:0 0 0 20px; overflow-y:hidden"
                                                                        >
                {% csrf_token %}
                <button type="submit" style="padding: 0; margin: 0; font-weight: 400;
                  background-color: transparent; color: white; border: none;">LOGOUT
                </button>
              </form>
              {% else %}
                <li><a href="{% url 'profiles:login' %}" style="text-decoration: none; color: white">Login</a></li>
              {% endif %}
            </ul>
        </div>
      </nav>
    </header>
    {% block content %} {% endblock %}

    <footer>
      <h3 style="margin-bottom: -10px;margin-top: 5px">DJANGO BANKING  WEB APP</h3>
      <small>&copy;eugeneemma7@gmail.com</small>
    </footer>
  </body>
</html>

django_projects/banking_app/profiles/templates/profiles/create_password.html
{% extends "profiles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block navigation %}
    <link rel="stylesheet" type="text/css" href="{% static 'transactions/deposit.css' %}" />
    <style>
      form{
        margin-top: 10px;
        padding: 10px;
      }
      li{
        list-style: none;
        color: red;
        text-align: center;
        margin: 10px 0;
      }
      
    </style>
    <title>Create Password</title>
  {% endblock %}
  <body>
    {% block content %}
    <h1 style="text-align: center; margin-top: 3vh;">
      Create Password
    </h1>
    <div class="contents">
      <div class="trans-forms">  
        {% if messages %}
          {% for msg in messages %}
            <p style="background-color: brown; padding-left: 40px; color: white;">{{msg}}</p> 
          {% endfor %}      
        {% endif %}
        <form action="" method="POST" id="post-form">
          {% csrf_token%} 
          {{form|crispy}}
          <button type="submit">Create Password</button>
        </form>
        <small><i>Already registered? <a href="{% url 'profiles:login' %}">Login Here</a></i></small>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

django_projects/banking_app/profiles/templates/profiles/customerprofile_form.html
{% extends "profiles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block navigation %}
    <link rel="stylesheet" type="text/css" href="{% static 'transactions/deposit.css' %}" />
    <style>
      form{
        margin-top: 10px;
        padding: 10px;
        height: 60vh;
        overflow-y: scroll;
      }
    </style>
    <title>Customer Profile</title>
  {% endblock %}
  <body>
    {% block content %}
    <h1 style="text-align: center; margin-top: 3vh;">CREATE PROFILE FOR CUSTOMER</h1>
    <div class="contents">
      {% if messages %}
        <div class="messages">
          {% for msg in messages %}
            {% if msg.tags == 'error' %}
              <p style="color: rgb(255, 47, 0)">{{msg}}</p>
            {% else %}
              <small style="color: rgb(0, 132, 255)">{{msg}}</small>
            {% endif %}
          {% endfor %}
        </div>
      {% endif %}
    
      <div class="trans-forms">
        <form method="POST" id="post-form" enctype="multipart/form-data">
          {% csrf_token %}
          {{form|crispy}}
          <button type="submit">Add Info</button>
        </form>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

django_projects/banking_app/profiles/templates/profiles/login.html
{% extends "profiles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block navigation %}
    <link rel="stylesheet" type="text/css" href="{% static 'transactions/deposit.css' %}" />
    <style>
      form{
        margin-top: 10px;
        padding: 10px;
      }
      li{
        list-style: none;
        color: red;
        text-align: center;
        margin: 10px 0;
      }
      form *{
        padding: 7px 10px;
      }
    </style>
    <title>Login</title>
  {% endblock %}
  <body>
    {% block content %}
    <h1 style="text-align: center; margin-top: 3vh;">
      Login To System
    </h1>
    <div class="contents">
      <div class="trans-forms">
        {% if messages %}
          {% for msg in messages %}
            {% if msg.tags == "error" %}
              <p style="background-color: brown; padding-left: 40px;">{{msg}}</p> 
            {% else %}
              <p style="background-color: #0cc; padding-left: 40px; color: white;">{{msg}}</p>
            {% endif %} 
          {% endfor %}      
        {% endif %}
        <form action="" method="POST" id="post-form">
          {% csrf_token%} 
          {{form|crispy}}
          <button type="submit">Login</button>
        </form>
        <small><i>New To System? <a href="{% url 'profiles:create_password' %}">Create password Here</a></i></small>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

django_projects/banking_app/profiles/templates/profiles/logout.html
{% extends "profiles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block navigation %}
    <link rel="stylesheet" type="text/css" href="{% static 'transactions/deposit.css' %}" />
    <style>
      form{
        background-color: transparent;
        box-shadow: none;
      }
      li{
        list-style: none;
        color: red;
        text-align: center;
        margin: 10px 0;
      }
      form *{
        padding: 7px 10px;
      }
      button{
        padding: 0;
        margin: 0;
      }
    </style>
    <title>Login</title>
  {% endblock %}
  <body>
    {% block content %}
    <h1 style="text-align: center; margin-top: 3vh;">Login To System</h1>
    <div class="contents"> 
      <div class="trans-forms">
        <form action="{% url 'profiles:login' %}" method="GET" id="post-form">
          {% csrf_token%} 
          {{form|crispy}}
          <button type="submit">Sign In again</button>
        </form>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

django_projects/banking_app/profiles/templates/profiles/user_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Inter:wght@100..900&family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'profiles/style/common.css' %}"
    />
    <link rel="icon" href="/media/logo.png">
    {% block navigation %}
    
    {% endblock %}
  </head>
  <body>
    <header>
      <nav>
        <div class="left">
          <a href="{% url 'transactions:pay_bills' %}">
            <img src="/media/logo.png" alt="LOGO" width="40px" height="40px">
            <h1>LA BANK</h1>
          </a>
        </div>
        <div class="right">
            {% if user.is_authenticated %}
            <ul>
              <small>Welcome, {{user.first_name}}.</small>
              <li><a href="{%url 'transactions:pay_bills' %}">TRANSACT</a></li>
              {% if user.account %}
                <li><a href="{% url 'profiles:user_account' user.account.id %}">ACCOUNT INFO</a></li>  
              {% endif %}
              <li><a href="{% url 'transactions:user_transactions' %}">HISTORY</a></li>
              <li><a href="{% url 'profiles:user_profile' user.id %}">PROFILE</a></li>
              <form action="{% url 'profiles:logout' %}" method="POST" style="background-color: transparent; 
                                                                        border:none; box-shadow: none; width: auto; 
                                                                        height: auto; margin-top:0; padding:0 0 0 20px; overflow-y:hidden"
                                                                        >
                {% csrf_token %}
                <button type="submit" style="padding: 0; margin: 0; font-weight: 400;
                  background-color: transparent; color: white; border: none;">LOGOUT
                </button>
              </form>
              {% else %}
                <li><a href="{% url 'profiles:login' %}" style="text-decoration: none; color: white">Login</a></li>
              {% endif %}
            </ul>
        </div>
      </nav>
    </header>
    {% block content %} {% endblock %}

    <footer>
      <h3 style="margin-bottom: -10px;margin-top: 5px">DJANGO BANKING  WEB APP</h3>
      <small>&copy;eugeneemma7@gmail.com</small>
    </footer>
  </body>
</html>

django_projects/banking_app/profiles/templates/profiles/user_form.html
{% extends "profiles/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
  {% block navigation %}
    <link rel="stylesheet" type="text/css" href="{% static 'transactions/deposit.css' %}" />
    <style>
      form{
        margin-top: 10px;
        padding: 10px;
      }
    </style>
    <title>Create User</title>
  {% endblock %}
  <body>
    {% block content %}
    <h1 style="text-align: center; margin-top: 3vh;">CREATE CUSTOMER</h1>
    <div class="contents">
        {% if messages %}
          <div class="messages">
              {% for msg in messages %}
                <p style="color: rgb(0, 132, 255)">{{msg}}</p>
                <small style="color: rgb(0, 132, 255)">{{msg.tags}}</small>
              {% endfor %}
            </div>
        {% endif %}
    
      <div class="trans-forms">
        <form action="" method="POST" id="post-form">
          {% csrf_token%} 
          {{form|crispy}}
          <button type="submit">Register User</button>
        </form>
      </div>
    </div>
    {% endblock %}
  </body>
</html>

django_projects/banking_app/profiles/templates/profiles/user_list.html
{% extends "profiles/base.html" %}
{% load static %}
{% block navigation %}
    <title>Customer Inspection</title>
    <link rel="stylesheet" href="{% static 'transactions/inspect.css' %}">
{% endblock %}

{% block content %}

<div class="container">
    <h1>CUSTOMER INSEPCTION</h1>
    <table>
        <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Telephone</th>
            <th>Email</th>
            <th>Date Joined</th>
            <th>Type</th>
        </tr>
        {% for customer in customers %}            
            {% if customer.type != "ADMIN" and customer.telephone != "AnonymousUser" %}
                <tr>
                    <td>{{customer.first_name}}</td>
                    <td>{{customer.last_name}}</td>
                    <td><a href="{% url 'transactions:single_acc_inspect' customer.id %}">{{customer.telephone}}</a></td>
                    <td>{{customer.email}}</td>
                    <td>{{customer.date_joined|date:"F d, Y"}}</td>
                    <td>{{customer.type}}</td>
                </tr>
            {% endif %}
        {% endfor %}
    </table>
</div>

{% endblock %}